# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ketch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ketch
pod ‘FBSDKCoreKit’
pod ‘FBSDKShareKit’
pod ‘FBSDKLoginKit’

pod ‘Firebase/Auth’
pod ‘Firebase/Database’

  target 'KetchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KetchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
